export const BEAR = 'bear'
export const CHICKEN = 'chicken'
export const PARROT = 'parrot'
export const DUCK = 'duck'
export const PENGUIN = 'penguin'
export const SOKOBAN = 'sokoban'
export const UI_PANEL = 'ui-panel'
export const FONT_NUMBERS = 'font-numbers'
